import type { Metadata } from "next";
import LegalShell from "../legal-shell";

export const metadata: Metadata = {
  title: "Privacy Policy — BillversTech",
  description: "How BillversTech collects, uses, protects and manages personal data.",
  alternates: { canonical: "/privacy" },
  openGraph: { title: "Privacy Policy — BillversTech", description: "How BillversTech manages personal data.", url: "/privacy", images: [] },
  twitter: { title: "Privacy Policy — BillversTech", description: "How BillversTech manages personal data.", images: [] },
};

export default function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy" intro="A plain-language account of the personal data BillversTech receives through this website, the limited reasons we use it, and the choices you have.">
      <section><h2>01 — Scope and responsibility</h2><p>This policy applies when you visit <a href="https://www.billverstech.com">www.billverstech.com</a>, submit an enquiry, contact us by phone, email or WhatsApp, or discuss a potential project with BillversTech. “BillversTech”, “we”, “us” and “our” refer to BILLVERSE TECHNOLOGIES (OPC) PRIVATE LIMITED, CIN U82990HR2026OPC148111, whose registered office is at C/O Rajesh Kumari, 1st Floor, Patiala Chowk, Jind, Haryana 126102, India.</p></section>
      <section><h2>02 — Information we may receive</h2><p>Depending on your interaction, we may receive:</p><ul><li><strong>Enquiry data:</strong> name, business name, service selection and the message you provide.</li><li><strong>Communications:</strong> phone number, email address, WhatsApp messages and correspondence records.</li><li><strong>Project material:</strong> requirements, content, brand assets and operational details shared for quoting or delivery.</li><li><strong>Technical data:</strong> IP address, browser or device information, timestamps and basic logs produced by hosting and security services.</li></ul><p>Do not submit account passwords, card details, government identifiers or unnecessary sensitive data through the enquiry form.</p></section>
      <section><h2>03 — How collection happens</h2><p>Most information comes directly from you. The website form creates a WhatsApp draft on your device; BillversTech does not receive it unless you review the draft and press send in WhatsApp. Limited technical logs may be created automatically to deliver and protect the site.</p></section>
      <section><h2>04 — Purposes of use</h2><p>We use personal data for specific, lawful business purposes:</p><ul><li>replying to enquiries and arranging discussions;</li><li>preparing proposals and delivering requested services;</li><li>maintaining project, support, contract and invoice records;</li><li>operating, securing and improving the website;</li><li>preventing misuse and meeting legal duties; and</li><li>sending promotional communication only where requested or otherwise permitted by law.</li></ul><p>If processing relies on consent, you may withdraw it by contacting us. Withdrawal does not change the lawfulness of earlier processing.</p></section>
      <section><h2>05 — WhatsApp and external services</h2><p>WhatsApp, email, telephone and linked websites are independent third-party services. Their privacy practices apply when you use them, and data may be processed outside India. Check the destination and message before transmitting personal information.</p></section>
      <section><h2>06 — Sharing</h2><p>BillversTech does not sell personal data. We may disclose only what is reasonably necessary to hosting, cloud, security, communications, analytics, accounting or professional-service providers; project collaborators bound by suitable confidentiality obligations; or authorities where disclosure is required by law.</p></section>
      <section><h2>07 — Storage and cross-border processing</h2><p>Service providers may process data in India or other locations. Where personal data is processed across borders, we use available contractual, technical and organisational measures and observe restrictions applicable under Indian law.</p></section>
      <section><h2>08 — Retention</h2><p>We retain information only while reasonably necessary for enquiry follow-up, project delivery, support, accounting, dispute handling and legal compliance. The exact period depends on the record and applicable obligations. When information is no longer required, we delete, anonymise or securely isolate it.</p></section>
      <section><h2>09 — Security</h2><p>We use reasonable access restrictions, trusted providers, updates, backups and organisational safeguards appropriate to our operations. No online transmission or storage method is infallible. Contact us promptly if you believe information shared with BillversTech has been compromised.</p></section>
      <section><h2>10 — Your rights and choices</h2><p>Subject to applicable law, you may request information about personal data we process, ask for access, correction or erasure where permitted, withdraw consent, or raise a grievance. As provisions apply, the Digital Personal Data Protection Act, 2023 may also provide nomination and complaint rights.</p><p>Email requests to <a href="mailto:support@billverstech.com">support@billverstech.com</a>. We may verify identity and may retain information where legally required or permitted.</p></section>
      <section><h2>11 — Children</h2><p>This is a business-services website and is not directed to children. We do not knowingly seek personal data from anyone under 18. Contact us if you believe a child has provided information so we can take appropriate action.</p></section>
      <section><h2>12 — Cookies and analytics</h2><p>The site does not currently use advertising cookies. Hosting and security services may create limited technical logs essential to operation. If non-essential analytics, advertising or similar tracking is introduced, this policy and any legally required notice or choice will be updated.</p></section>
      <section><h2>13 — Updates and contact</h2><p>We may revise this policy when our practices, providers or legal obligations change. The current version and date will remain on this page. Questions or grievances can be sent to <a href="mailto:support@billverstech.com">support@billverstech.com</a>, raised by calling <a href="tel:+917082688288">+91 70826 88288</a> or <a href="tel:+911681460068">01681-460068</a>, or mailed to our registered office.</p></section>
    </LegalShell>
  );
}
